version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: autoya-backend:ci
    container_name: autoya-backend-qa
    ports:
      - "11080:8080"
    env_file:
      - .env.qa
    depends_on:
      - postgres-qa
      - redis-qa
      - minio-qa

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: autoya-frontend:ci
    container_name: autoya-frontend-qa
    ports:
      - "11081:80"
    env_file:
      - .env.dev
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-qa
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "11543:5432"
    volumes:
      - postgres_data-qa:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-qa
    ports:
      - "11679:6379"
    volumes:
      - redis_data-qa:/data

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-qa
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "11090:9000"
      - "11091:9001"
    volumes:
      - minio_data:/data

  # ðŸ‘‡ Servicio para configurar polÃ­tica pÃºblica automÃ¡ticamente
  minio-setup-qa:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio-qa
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set myminio ${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p myminio/autoya-${BRANCH} || true &&
      mc anonymous set download myminio/autoya-${BRANCH} &&
      echo 'âœ… Bucket autoya-dev pÃºblico listo.'
      "

volumes:
  postgres_data-qa:
  redis_data-qa:
  minio_data-qa:
